# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mitja Jež
email: mitja@jež.si
description: >
  Me and my open source story on the way of building tools for transition
  into a Resource Based Economy by The Venus Project.
repository: mitjajez/SONCE
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mitja.xn--je-3va.si" # the base hostname & protocol for your site
permalink: /blog/:year/:month/:title
diaspora_username: mitjajez
github_username: mitjajez
twitter_username: mitjajez

# Build settings
markdown: kramdown

exclude: [vendor]

# Plugins
plugins:
   - jekyll-mentions
   - jemoji
   - jekyll-redirect-from
   - jekyll-sitemap
   - jekyll-feed
